name: patent-platform
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - pytorch>=1.9.0
  - scikit-learn>=0.24.2
  - matplotlib>=3.4.2
  - pyyaml>=5.4.1
  - django>=3.2.0
  - tqdm>=4.61.0
  - pytest>=6.2.5
  - python-dotenv>=0.19.0
  - requests>=2.26.0
  - scipy>=1.7.0
  - seaborn>=0.11.2
  - tensorboard>=2.6.0
  - pip:
    - torch-geometric>=2.0.0
    - neo4j>=4.4.0
    - djangorestframework>=3.12.0
    - jieba>=0.42.1 