global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'python-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['python-service:5000']

  - job_name: 'neo4j'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['neo4j:7474']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 